### ISSUE TITLE
Does it suppoerts only nor based chips?

### ISSUE THREAD

**Issue by asmitaj08** [alainiamburg/sniffROM#5]
Hello,
I had been trying to read 128 MB SPI nand flash PN26Q01AWSIUG "http://pro0fc108.hkpic1.websiteonline.cn/upload/PN26Q01AWSIUG.pdf" but was not successful. I had a query that does this tool only suppoerts nor based chips?

Regards
Asmita

**Comment by alainiamburg** [comment]
Hi Asmita,

The first advice i would give is make sure you have a proper Saleae capture
(e.g. your capture rate was sufficient for the speed of your device).

sniffROM recognizes the commands in the commands.xlsx file and is able to
parse the most commonly used ones (read, write, etc). So as long as your
device uses the same commands (which briefly looking at the datasheet seems
to be the case) then the tool *should* work. One caveat is that "quad I/O
mode" commands are not currently supported.

Do you have any error output, or what are you seeing?

-alain

**Comment by asmitaj08** [comment]
Hello,
I am getting error like :

~/sniffROM$ python sniffROM.py flashSpiData.csv -o flashData.bin --summary
Parsing SPI data...

Traceback (most recent call last):
  File "sniffROM.py", line 663, in <module>
    highest_byte+1, args.o, bytes_sniffed, ((bytes_sniffed / float(highest_byte)) * 100.0), bytes_sniffed_written)
ZeroDivisionError: float division by zero


Kindly let me know about this issue.

Regards
Asmita

**Comment by asmitaj08** [comment]
Hello,
The above error was when I took data for 180 seconds , after taking samples for 120 seconds, I got error as :


~/sniffROM$ python sniffROM.py f1.csv -o flashData.bin --summary
Parsing SPI data...

Traceback (most recent call last):
  File "sniffROM.py", line 417, in <module>
    elif ((command == 0x03) or       # Read
NameError: name 'command' is not defined

**Comment by alainiamburg** [comment]
Asmita,

Those errors look strange.. based on the source code I don't know how they
would happen. Can you confirm you have the latest code free of
modifications? And were you ever able to use the tool successfully for
other flash chips? Try running the tool with "-vv" for more verbosity.

Would you be able to send the first 40 or so lines of the CSV input that
you're using? It currently needs to match the format created by the
Saleae's default SPI analyzer.

-alain

**Comment by asmitaj08** [comment]
Hello,
I cloned the repository using
git clone https://github.com/alainiamburg/sniffROM.git

Currently I have tried only with this chip. Same error.
~/sniffROM$ python sniffROM.py f1.csv -o flashData.bin -vv
Parsing SPI data...

Traceback (most recent call last):
  File "sniffROM.py", line 417, in <module>
    elif ((command == 0x03) or       # Read
NameError: name 'command' is not defined


The first 40 bytes I am copying here -


Time [s] | Packet ID | MOSI | MISO
-- | -- | -- | --
2.8868975 |   | 0xFF | 0x04
2.97137825 |   | 0xFF | 0x15
2.97140325 |   | 0xFF | 0x55
2.97142825 |   | 0xFF | 0x0B
2.97160825 |   | 0xFF | 0x38
2.97162775 |   | 0xFF | 0x16
2.9717005 |   | 0xFF | 0x52
2.97187225 |   | 0xFF | 0x00
2.97191225 |   | 0xFF | 0x02
2.97195225 |   | 0xFF | 0x04
2.97212725 |   | 0xFF | 0x20
2.97213775 |   | 0xFF | 0xC9
2.9721805 |   | 0xFF | 0x21
2.97223025 |   | 0xFF | 0x5C
2.97240125 |   | 0xFF | 0x00
2.97244125 |   | 0xFF | 0x00
2.97248125 |   | 0xFF | 0x1A
2.9726555 |   | 0xFF | 0x1F
2.97266925 |   | 0xFF | 0x88
2.97269175 |   | 0xFF | 0xF2
2.97275225 |   | 0xFF | 0xB4
2.9729205 |   | 0xFF | 0x00
2.9729605 |   | 0xFF | 0x12
2.97299 |   | 0xFF | 0xE8
2.97317525 |   | 0xFF | 0x01
2.97319875 |   | 0xFF | 0x00
2.97328175 |   | 0xFF | 0x4B
11.91448775 |   | 0xFF | 0x03
11.9147025 |   | 0xFF | 0x39
11.914757 |   | 0xFF | 0x04
11.914998 |   | 0xFF | 0x13
11.91522075 |   | 0xFF | 0x33
11.91545875 |   | 0xFF | 0xBD
11.91553425 |   | 0xFF | 0x4F
11.91571775 |   | 0xFF | 0xFF
11.91579675 |   | 0xFF | 0xFF
11.91597825 |   | 0xFF | 0xFF
11.9160045 |   | 0xFF | 0xFE
11.91623825 |   | 0xFF | 0x22
11.91624575 |   | 0xFF | 0x00
11.9163265 |   | 0xFF | 0x22
11.91650125 |   | 0xFF | 0x00
11.916541 |   | 0xFF | 0x00
11.91680075 |   | 0xFF | 0xF0
11.91687275 |   | 0xFF | 0x94
11.91703675 |   | 0xFF | 0xA3
11.9170545 |   | 0xFF | 0x05
11.917096 |   | 0xFF | 0x3C
11.9178395 |   | 0xFF | 0x14

**Comment by alainiamburg** [comment]
Where are the packet IDs?

As for the data, it looks like either your miso/mosi wires are not
connected properly or you caught the device in the middle of a read.

I recommend you read the sniffROM wiki closely and make sure you are
following the steps correctly. Make sure you understand how the SPI
protocol works and get a proper logic trace capture (ideally start taking
the capture first and then power on the device you are analyzing). Keep in
mind the read/write commands are sent to the flash on MOSI and the flash
data comes back on MISO.

-alain

**Comment by alainiamburg** [comment]
closing this due to inactivity
